### ISSUE TITLE
Sort Problems after Sorting with Mobile Version

### ISSUE THREAD

**Issue by Luc1412** [BtoBastian/bStats-Metrics#22] opened 2017-08-15 21:17 UTC
I sort the charts from my Plugin with my Phone in the Webbrowser. That was very buggy and didn't worke. After this it didn't worke on my Pc too.

Informations:
   Phone Browser: Samsung Internet Beta
   Pc Browser: Opera Dev
   Phone: Samsung Galaxy S7 edge
   PluginName: EasyMaintenance
   Version: Full Version(Not Lite) Bukkit Edition

**Comment by BtoBastian** [comment] 2018-02-17 13:42
Should be fixed since ~3 month (duplicate of https://github.com/BtoBastian/bStats/issues/23)

**Closed by BtoBastian** 2018-02-17 13:42 UTC
Labels: bug
